services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  
  clinical_data:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
